-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvBxRVKrnLpC5C8rx
8yvlS/XO/Tl9AdwfNpB/RVp0VVqgCgYIKoZIzj0DAQehRANCAATgQEywLa5uRGKj
Oxq3FXo29nKSWR9mr8cqztmqfPu6jVeyrRp9SYJFxUW9V+En0j8NtyHsPhiBV058
XER7MAnJ
-----END PRIVATE KEY-----